#!/bin/bash
#SBATCH --partition=long
#SBATCH --nodes=23
#SBATCH --tasks-per-node=40
#SBATCH -J cmaq_op_00_0_p_24            # Job name
#SBATCH -t 48:00:00                     # Walltime limit
#SBATCH -p long                         # queue to be used
#SBATCH --exclusive                     # Exclusive use of nodes
#SBATCH -o cmaq_mpi.%j.out              # output name
#SBATCH --mem=10G

source /users/intel-test/oneapi/setvars.sh

# enable MPI pinning and use only half of the cores of each socket
#export I_MPI_PIN=1
#export I_MPI_PIN_PROCESSOR_LIST="0,1,2,3,4,5,6,7,8,9,20,21,22,23,24,25,26,27,28,29"
#export I_MPI_DEBUG=5 # optional: print pinning


#export OMP_NUM_THREADS=2
#export MP_SINGLE_THREAD="no"

echo "start test cmaq" 
datum=$1
/users/oko001/cmaq_oper_scripts/CMAQ_v5.3.3_oper/CCTM/scripts/run_oper_00_0_24.csh $1
echo "end test cmaq"



