#!/bin/bash

datum=$1
/users/p6065/anaconda3/envs/supergeo/bin/python -u /users/oko001/cmaq_oper_scripts/bc_creator/bc_CAMS_downl_and_check.py ${datum}> /work/users/oko001/cmaq_oper_logs/bc_creator_logs/LOG_downl_${datum} 2>&1
